name: Enhancement
description: Propose an enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: why
    attributes:
      label: Motivation
      description: "Why this change?"
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: "What should change?"

