name: Proof Bundle Hashes

on:
  pull_request:
    paths:
      - 'proofs/**'
      - 'tools/hash_bundle.py'

jobs:
  hash:
    name: Generate and Upload SHA256SUMS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run proof hasher
        run: |
          python tools/hash_bundle.py

      - name: Upload SHA256SUMS.txt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proof-hashes
          path: |
            proofs/**/SHA256SUMS.txt
          if-no-files-found: ignore
